// components/qualifications/ApplicationModal.tsx
import React, { useState } from 'react';
import { X, Upload, FileText, CheckCircle, AlertCircle } from 'lucide-react';

interface ApplicationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (applicationData: any) => void;
  mode: 'create' | 'view';
  application: any | null;
}

export default function ApplicationModal({ 
  isOpen, 
  onClose, 
  onSave, 
  mode, 
  application 
}: ApplicationModalProps) {
  const [formData, setFormData] = useState({
    applicantName: application?.applicantName || '',
    qualification: application?.qualification || '',
    documents: application?.documents || {
      applicationLetter: null,
      motivation: null,
      reference: null,
      acrLetter: null
    }
  });
  const [report, setReport] = useState(application?.report || null);
  const [isVerified, setIsVerified] = useState(application?.status === 'verified');

  if (!isOpen) return null;

  const handleFileUpload = (documentType: string, file: File) => {
    setFormData({
      ...formData,
      documents: {
        ...formData.documents,
        [documentType]: file.name
      }
    });
  };

  const handleVerifyAndGenerateReport = () => {
    // Create a better formatted draft report
    const allDocsPresent = 
      formData.documents.applicationLetter &&
      formData.documents.motivation &&
      formData.documents.reference &&
      formData.documents.acrLetter;

    const draftReport = `
╔════════════════════════════════════════════════════════════╗
║                 GATE EVALUATION REPORT                     ║
╠════════════════════════════════════════════════════════════╣
║ Application ID: ${application?.id || 'New Application'}                          
║ Applicant: ${formData.applicantName}                                
║ Qualification: ${formData.qualification}                            
║ Date: ${new Date().toLocaleDateString()}                                  
╚════════════════════════════════════════════════════════════╝

📋 DOCUMENT VERIFICATION SUMMARY
═══════════════════════════════════════════════════════════════

1. Application Letter:     ${formData.documents.applicationLetter ? '✓ PRESENT' : '✗ MISSING'}
   File: ${formData.documents.applicationLetter || 'Not uploaded'}

2. Motivation Letter:      ${formData.documents.motivation ? '✓ PRESENT' : '✗ MISSING'}
   File: ${formData.documents.motivation || 'Not uploaded'}

3. Reference Letter:       ${formData.documents.reference ? '✓ PRESENT' : '✗ MISSING'}
   File: ${formData.documents.reference || 'Not uploaded'}

4. ACR Letter:            ${formData.documents.acrLetter ? '✓ PRESENT' : '✗ MISSING'}
   File: ${formData.documents.acrLetter || 'Not uploaded'}

═══════════════════════════════════════════════════════════════

📊 OVERALL STATUS: ${allDocsPresent ? '✅ COMPLETE' : '❌ INCOMPLETE'}

${allDocsPresent ? 
  '✓ All required documents have been uploaded. Application is ready for review.' : 
  '⚠️ Some required documents are missing. Please upload all documents before proceeding.'}

═══════════════════════════════════════════════════════════════

🏁 RECOMMENDATION:
${allDocsPresent ? 
  'PROCEED TO NEXT STAGE - Application meets minimum requirements.' : 
  'HOLD - Please upload all required documents.'}

Generated by: System
Time: ${new Date().toLocaleTimeString()}
    `;

    setReport({
      verified: true,
      draftReport: draftReport,
      verificationDate: new Date().toISOString().split('T')[0]
    });
    setIsVerified(true);
  };

  const handleSubmit = () => {
    onSave({
      ...formData,
      report: report,
      status: 'submitted'
    });
  };

  const handleSave = () => {
    onSave({
      ...formData,
      report: report,
      status: 'draft'
    });
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b">
          <h2 className="text-xl font-semibold">
            {mode === 'create' ? 'Create New Application' : 'Application Details'}
          </h2>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-700">
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          <div className="space-y-6">
            {/* Application Form */}
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Applicant Name
                </label>
                <input
                  type="text"
                  value={formData.applicantName}
                  onChange={(e) => setFormData({ ...formData, applicantName: e.target.value })}
                  disabled={mode === 'view' && application?.status !== 'draft'}
                  className="w-full border rounded px-3 py-2"
                  placeholder="Enter applicant name"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Qualification
                </label>
                <input
                  type="text"
                  value={formData.qualification}
                  onChange={(e) => setFormData({ ...formData, qualification: e.target.value })}
                  disabled={mode === 'view' && application?.status !== 'draft'}
                  className="w-full border rounded px-3 py-2"
                  placeholder="Enter qualification"
                />
              </div>

              {/* Document Upload Section */}
              <div className="border rounded-lg p-4">
                <h3 className="font-medium mb-3">Supporting Documentation</h3>
                <div className="space-y-3">
                  {[
                    { id: 'applicationLetter', label: 'Application Letter' },
                    { id: 'motivation', label: 'Motivation' },
                    { id: 'reference', label: 'Reference' },
                    { id: 'acrLetter', label: 'ACR Letter' }
                  ].map((doc) => (
                    <div key={doc.id} className="flex items-center justify-between">
                      <span className="text-sm">{doc.label}</span>
                      <div className="flex items-center space-x-2">
                        {formData.documents[doc.id] && (
                          <span className="text-sm text-green-600 flex items-center gap-1">
                            <CheckCircle className="w-4 h-4" />
                            {formData.documents[doc.id]}
                          </span>
                        )}
                        {(mode === 'create' || application?.status === 'draft') && (
                          <input
                            type="file"
                            onChange={(e) => {
                              if (e.target.files?.[0]) {
                                handleFileUpload(doc.id, e.target.files[0]);
                              }
                            }}
                            className="text-sm"
                          />
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Verification and Report Section */}
            {mode === 'view' && application?.status === 'draft' && !report && (
              <div className="border-t pt-4">
                <button
                  onClick={handleVerifyAndGenerateReport}
                  className="bg-purple-600 text-white px-4 py-2 rounded hover:bg-purple-700"
                >
                  Gate Evaluation Check & Generate Draft Report
                </button>
              </div>
            )}

            {/* Report Display */}
            {report && (
              <div className="border-t pt-4">
                <h3 className="font-medium mb-2">Draft Report</h3>
                <div className="bg-gray-900 text-green-400 p-4 rounded-lg font-mono text-sm overflow-x-auto">
                  <pre className="whitespace-pre-wrap">
                    {report.draftReport}
                  </pre>
                </div>
                <p className="text-sm text-gray-500 mt-2">
                  Verified on: {report.verificationDate}
                </p>
              </div>
            )}

            {/* Submit Button */}
            {mode === 'view' && report && application?.status === 'draft' && (
              <div className="border-t pt-4">
                <button
                  onClick={handleSubmit}
                  className="bg-green-600 text-white px-6 py-2 rounded hover:bg-green-700"
                >
                  Submit Application
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end space-x-2 p-6 border-t">
          <button
            onClick={onClose}
            className="px-4 py-2 border rounded hover:bg-gray-50"
          >
            Cancel
          </button>
          {mode === 'create' && (
            <button
              onClick={handleSave}
              className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
            >
              Create Application
            </button>
          )}
          {mode === 'view' && application?.status === 'draft' && !report && (
            <button
              onClick={handleSave}
              className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
            >
              Save Draft
            </button>
          )}
        </div>
      </div>
    </div>
  );
}